import type { Metadata } from "next";
// import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

import { QueryProvider } from "@/providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Orseek",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* <ClerkProvider> */}
        <QueryProvider>{children}</QueryProvider>
        {/* </ClerkProvider> */}
      </body>
    </html>
  );
}
